name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the frontend Docker image
      - name: Build frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./bitcoin-explorer-frontend
          file: ./bitcoin-explorer-frontend/Dockerfile
          platforms: linux/amd64
          push: false

      # Build the backend Docker image
      - name: Build backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./node-backend
          file: ./node-backend/Dockerfile
          platforms: linux/amd64
          push: false

      # Build the bitcoin-ingestion Docker image
      - name: Build ingestion Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./bitcoin_ingestion
          file: ./bitcoin_ingestion/Dockerfile
          platforms: linux/amd64
          push: false
